name: tests

on: [push]

jobs:
  run_tests:
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v1
    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_13.0.app && /usr/bin/xcodebuild -version
    - name: Build
      run: xcodebuild -configuration Debug build -project CocoaActivityCounter.xcodeproj | xcpretty && exit ${PIPESTATUS[0]}
    - name: Find app
      run: find . -name CocoaActivityCounter.app
    - name: Archive app
      uses: actions/upload-artifact@v2
      with:
	name: app
	path: CocoaActivityCounter.app

